# Generated by Django 4.1.5 on 2023-02-03 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.basemodel')),
                ('title', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=200)),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=200)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('years_in_workplace', models.TextField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=200)),
                ('picture', models.ImageField(blank=True, max_length=200, upload_to='employee/')),
                ('educational_status', models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('High School', 'High School'), ('Phd', 'Phd'), ('Masters', 'Masters')], max_length=200)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('administration.basemodel',),
        ),
    ]
