# Generated by Django 4.1.5 on 2023-02-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basemodel',
            table='base_model',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
        migrations.AlterModelTable(
            name='globalcharges',
            table='global_charges',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
