# Generated by Django 4.1.5 on 2023-06-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcharges',
            name='id',
        ),
        migrations.AddField(
            model_name='globalcharges',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=11, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.basemodel'),
            preserve_default=False,
        ),
    ]
