# Generated by Django 4.1.5 on 2023-02-03 08:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='current_salary',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='years_in_workplace',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
