# Generated by Django 4.1.5 on 2023-09-18 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0003_branchstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_status_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branchstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_status_updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
