# Generated by Django 4.1.5 on 2023-09-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_branch_status_alter_branch_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
