# Generated by Django 4.1.5 on 2024-01-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_withdrawsavings_delete_widthdrawsavings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawsavings',
            old_name='received_date',
            new_name='withdrawn_date',
        ),
    ]
