# Generated by Django 4.1.5 on 2023-07-26 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_alter_residentialareas_created_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_repayment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maintenance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('general_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_processing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('affidavit_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_contributions', to='members.members')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_contributions_instance_creator', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_contirbutions_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_contributions',
                'ordering': ['-received_date'],
            },
        ),
    ]
