# Generated by Django 4.1.5 on 2023-08-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycontributions',
            options={'ordering': ['received_date']},
        ),
    ]
