# Generated by Django 4.1.5 on 2023-09-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_alter_dailycontributions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycontributions',
            options={'ordering': ['-received_date']},
        ),
    ]
