# Generated by Django 4.1.5 on 2024-01-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_alter_dailycontributions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycontributions',
            options={'ordering': ['-collection_date']},
        ),
        migrations.RenameField(
            model_name='dailycontributions',
            old_name='received_date',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='dailycontributions',
            old_name='loan_insurance',
            new_name='loan_form',
        ),
        migrations.RenameField(
            model_name='dailycontributions',
            old_name='loan_processing',
            new_name='loan_insurance_fee',
        ),
        migrations.RenameField(
            model_name='dailycontributions',
            old_name='account_no',
            new_name='member',
        ),
        migrations.AddField(
            model_name='dailycontributions',
            name='loan_processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailycontributions',
            name='passbook',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailycontributions',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
