# Generated by Django 4.1.5 on 2023-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_lipanampesacallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_time', models.CharField(max_length=100)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_short_code', models.CharField(max_length=100)),
                ('bill_ref_number', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('org_account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('third_party_trans_id', models.CharField(max_length=100)),
                ('msisdn', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
