# Generated by Django 4.1.5 on 2023-06-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits_account',
            name='account_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits_account', to='members.members'),
        ),
    ]
