# Generated by Django 4.1.5 on 2023-08-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
