# Generated by Django 4.1.5 on 2023-08-16 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='todo',
            name='assigned_to',
            field=models.ManyToManyField(related_name='todo_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
