# Generated by Django 4.1.5 on 2023-02-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_staffaccount_current_salary_staffaccount_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User')], max_length=200, null=True),
        ),
    ]
