# Generated by Django 4.1.5 on 2023-07-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_staffaccount_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffaccount',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
