# Generated by Django 4.1.5 on 2023-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_staffaccount_fullname_alter_staffaccount_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
