# Generated by Django 4.1.5 on 2023-07-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_staffaccount_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffaccount',
            name='fullname',
        ),
    ]
