# Generated by Django 4.1.5 on 2023-07-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_staffaccount_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffaccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='user_permissions',
        ),
    ]
