# Generated by Django 4.1.5 on 2023-09-18 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_branch'),
        ('authentication', '0014_alter_staffaccount_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.branch'),
        ),
    ]
