# Generated by Django 4.1.5 on 2023-09-25 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_staffaccount_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
