# Generated by Django 4.1.5 on 2023-09-25 07:45

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20230925_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
