# Generated by Django 4.1.5 on 2023-09-25 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_staffaccount_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
