# Generated by Django 4.1.5 on 2023-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_staffaccount_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='is_authenticator',
            field=models.BooleanField(default=False),
        ),
    ]
