# Generated by Django 4.1.5 on 2023-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_staffaccount_is_authenticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='otp_base32',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
