# Generated by Django 4.1.5 on 2024-01-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_staffaccount_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
