# Generated by Django 4.1.5 on 2023-06-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.basemodel')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/')),
            ],
            options={
                'db_table': 'documents',
            },
            bases=('authentication.basemodel',),
        ),
        migrations.CreateModel(
            name='documentType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.basemodel')),
                ('name', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('KRA Pin', 'KRA Pin'), ('Drivers License', 'Drivers License')], max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'document_type',
            },
            bases=('authentication.basemodel',),
        ),
        migrations.CreateModel(
            name='Loan_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'loan_status',
            },
        ),
        migrations.CreateModel(
            name='Loan_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField()),
                ('need_collateral', models.BooleanField(help_text='does this type of Loan need Coollateral')),
                ('need_guarantor', models.BooleanField(help_text='does this type of loan need a gurantor')),
                ('min_amount_allowed', models.IntegerField(blank=True, null=True)),
                ('max_amount_allowed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_type',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount_repaid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_repaid', models.DateField(blank=True, null=True)),
                ('loan_form_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_insurance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'loans_repayment',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('payment_frequency', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('quaterly', 'quaterly'), ('bi-annual', 'bi-annual'), ('yearly', 'yearly')], max_length=50)),
            ],
            options={
                'db_table': 'loans',
            },
        ),
    ]
