# Generated by Django 4.1.5 on 2023-06-12 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('KRA Pin', 'KRA Pin'), ('Drivers License', 'Drivers License')], max_length=50)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentType_instance_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentType_instance_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Loan_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DISBURSED', 'Disbursed'), ('REPAID', 'Repaid'), ('DEFAULT', 'Default'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], max_length=60, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanStatus_instance_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanStatus_instance_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_status',
            },
        ),
        migrations.CreateModel(
            name='Loan_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField()),
                ('need_collateral', models.BooleanField(help_text='does this type of Loan need Coollateral')),
                ('need_guarantor', models.BooleanField(help_text='does this type of loan need a gurantor')),
                ('min_amount_allowed', models.IntegerField(blank=True, null=True)),
                ('max_amount_allowed', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loantype_instance_creator', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(help_text='Include documents that are needed here for this particular loan.. You can go to the document section to add or delete document', to='loans.documenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loantype_instance_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_type',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('payment_frequency', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('quaterly', 'quaterly'), ('bi-annual', 'bi-annual'), ('yearly', 'yearly')], max_length=50)),
                ('guarantors', models.ManyToManyField(related_name='guarantors', to='members.members')),
                ('lendee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower', to='members.members')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan_type')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loan_status')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount_repaid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_repaid', models.DateField(blank=True, null=True)),
                ('loan_form_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_insurance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loans')),
            ],
            options={
                'db_table': 'loans_repayment',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents_instance_creator', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.documenttype')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_documents', to='loans.loans')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents_instance_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
