# Generated by Django 4.1.5 on 2023-06-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='guarantors',
            field=models.ManyToManyField(related_name='guarantors', to='members.members'),
        ),
        migrations.AddField(
            model_name='loans',
            name='lendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower', to='members.members'),
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan_type'),
        ),
        migrations.AddField(
            model_name='loans',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan_status'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loans'),
        ),
        migrations.AddField(
            model_name='loan_type',
            name='documents',
            field=models.ManyToManyField(help_text='Include documents that are needed here for this particular loan.. You can go to the document section to add or delete document', to='loans.documenttype'),
        ),
        migrations.AddField(
            model_name='documents',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.documenttype'),
        ),
        migrations.AddField(
            model_name='documents',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_documents', to='loans.loans'),
        ),
    ]
