# Generated by Django 4.1.5 on 2023-06-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='date_repaid',
            new_name='payment_date',
        ),
        migrations.AlterField(
            model_name='loans',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
