# Generated by Django 4.1.5 on 2023-02-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documents',
            table='documents',
        ),
        migrations.AlterModelTable(
            name='documenttype',
            table='document_type',
        ),
        migrations.AlterModelTable(
            name='loan_type',
            table='loan_type',
        ),
        migrations.AlterModelTable(
            name='loans',
            table='loans',
        ),
    ]
