# Generated by Django 4.1.5 on 2023-06-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_date_repaid_loanrepayment_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrepayment',
            name='late_charges',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='loan_form_fee',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='loan_insurance_fee',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='loan_interest',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='loan_processing_fee',
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanrepayment_set', to='loans.loans'),
        ),
    ]
