# Generated by Django 4.1.5 on 2023-02-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_type_documents_loan_type_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.documents'),
        ),
    ]
