# Generated by Django 4.1.5 on 2023-06-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_type',
            name='id',
        ),
        migrations.AddField(
            model_name='loan_type',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=12, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.basemodel'),
            preserve_default=False,
        ),
    ]
