# Generated by Django 4.1.5 on 2023-06-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loans.document_status'),
            preserve_default=False,
        ),
    ]
