# Generated by Django 4.1.5 on 2023-05-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_type_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='repaid_amount',
        ),
    ]
