# Generated by Django 4.1.5 on 2023-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loan_type_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_type',
            name='documents',
        ),
        migrations.AddField(
            model_name='loan_type',
            name='documents',
            field=models.ManyToManyField(help_text='Include documents that are needed here for this particular loan.. You can go to the document section to add or delete document', to='loans.documenttype'),
        ),
    ]
