# Generated by Django 4.1.5 on 2023-06-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loans_next_interest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='is_fixed_interest',
            field=models.BooleanField(default=1, help_text='does this type of Loan need Coollateral'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanrepayment_set', to='loans.loans'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='days_after_late_repayment',
            field=models.IntegerField(default=30),
        ),
    ]
