# Generated by Django 4.1.5 on 2023-02-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loan_type_documents_loan_type_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_type',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
