# Generated by Django 4.1.5 on 2023-05-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loans_repayment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'loan status',
            },
        ),
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan_status'),
        ),
    ]
