# Generated by Django 4.1.5 on 2023-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanproduct_is_fixed_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='is_insterest_included',
            field=models.BooleanField(default=1, help_text='is the interest amount already included in the amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans',
            name='total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='is_fixed_interest',
            field=models.BooleanField(help_text='is the interest amount fixed or reducing'),
        ),
    ]
