# Generated by Django 4.1.5 on 2023-06-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loanrepayment_is_insterest_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
