# Generated by Django 4.1.5 on 2023-02-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_type_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='late_charge',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='loan_interest',
        ),
    ]
