# Generated by Django 4.1.5 on 2023-05-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_status_alter_loans_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan_status',
            table='loan_status',
        ),
    ]
