# Generated by Django 4.1.5 on 2023-02-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_image'),
        ('loans', '0007_remove_loans_late_charge_remove_loans_loan_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='guarantors',
        ),
        migrations.AddField(
            model_name='loans',
            name='guarantors',
            field=models.ManyToManyField(related_name='guarantors', to='members.members'),
        ),
    ]
