# Generated by Django 4.1.5 on 2023-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loan_status_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_status',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
