# Generated by Django 4.1.5 on 2023-05-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loan_status_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_status',
            old_name='status',
            new_name='status_name',
        ),
    ]
