# Generated by Django 4.1.5 on 2023-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_remove_loans_guarantors_loans_guarantors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='issue_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(),
        ),
    ]
