# Generated by Django 4.1.5 on 2023-06-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_installment_alter_loanproduct_interest_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loans',
            table=None,
        ),
    ]
