# Generated by Django 4.1.5 on 2023-05-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_rename_status_loan_status_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
