# Generated by Django 4.1.5 on 2023-06-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loans_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='installment_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loans',
            name='total_installments',
            field=models.IntegerField(default=0),
        ),
    ]
