# Generated by Django 4.1.5 on 2023-06-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_installment_installment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='installment_schedule',
            field=models.JSONField(default=list),
        ),
    ]
