# Generated by Django 4.1.5 on 2023-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_remove_loanrepayment_is_insterest_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='total_installment_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
