# Generated by Django 4.1.5 on 2023-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loans_excess_payment_alter_loans_remaining_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='excess_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
