# Generated by Django 4.1.5 on 2023-06-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_members_have_loan'),
        ('loans', '0016_alter_loans_excess_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='consecutive_missed_payments',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='days_after_late_repayment',
        ),
        migrations.AlterField(
            model_name='loans',
            name='application_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loans',
            name='grace_period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member', to='members.members'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loans',
            name='term',
            field=models.IntegerField(),
        ),
    ]
