# Generated by Django 4.1.5 on 2023-06-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_remove_loans_consecutive_missed_payments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='late_charge',
            new_name='total_late_charge',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='next_interest_amount',
        ),
    ]
