# Generated by Django 4.1.5 on 2023-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_rename_late_charge_loans_total_late_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='total_late_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
