# Generated by Django 4.1.5 on 2023-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_alter_loans_total_late_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
