# Generated by Django 4.1.5 on 2023-06-19 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='loanAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], max_length=20, null=True)),
                ('value', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanAsset_instance_creator', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanAsset_instance_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_asset',
            },
        ),
        migrations.CreateModel(
            name='assetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(null=True, upload_to='assetdocuments/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assetDocument_instance_creator', to=settings.AUTH_USER_MODEL)),
                ('proof_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanager.loanasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assetDocument_instance_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_document',
            },
        ),
    ]
