# Generated by Django 4.1.5 on 2023-05-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '__first__'),
        ('loans', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanAsset',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.basemodel')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('in review', 'in review'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=20, null=True)),
                ('value', models.IntegerField(null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
            options={
                'db_table': 'loan_asset',
            },
            bases=('administration.basemodel',),
        ),
        migrations.CreateModel(
            name='assetDocument',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.basemodel')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(null=True, upload_to='assetdocuments/')),
                ('proof_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanager.loanasset')),
            ],
            options={
                'db_table': 'asset_document',
            },
            bases=('administration.basemodel',),
        ),
    ]
