# Generated by Django 4.1.5 on 2023-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanasset',
            name='file',
            field=models.FileField(null=True, upload_to='assetdocuments/'),
        ),
        migrations.DeleteModel(
            name='assetDocument',
        ),
    ]
