# Generated by Django 4.1.5 on 2023-02-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='asset',
        ),
        migrations.AlterModelTable(
            name='assetdocument',
            table='asset_document',
        ),
    ]
