# Generated by Django 4.1.5 on 2023-06-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('assetmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanasset',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans'),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='proof_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanager.loanasset'),
        ),
    ]
