# Generated by Django 4.1.5 on 2023-02-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0002_loanasset_file_delete_assetdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanasset',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanasset',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
