# Generated by Django 4.1.5 on 2023-02-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('assetmanager', '0003_alter_loanasset_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanasset',
            name='file',
        ),
        migrations.CreateModel(
            name='assetDocument',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.basemodel')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(null=True, upload_to='assetdocuments/')),
                ('proof_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanager.loanasset')),
            ],
            options={
                'db_table': 'asset_document',
            },
            bases=('administration.basemodel',),
        ),
    ]
