# Generated by Django 4.1.5 on 2023-05-05 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='residential_areas',
            fields=[
                ('area_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'residential_areas',
            },
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('names', models.CharField(blank=True, max_length=255, null=True)),
                ('mbr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('id_no', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_nos', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/passport_photo/')),
                ('kra_pin', models.CharField(blank=True, max_length=60, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('residential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.residential_areas')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
