# Generated by Django 4.1.5 on 2023-02-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='members',
            table='members',
        ),
        migrations.AlterModelTable(
            name='residential_areas',
            table='residential_areas',
        ),
    ]
