# Generated by Django 4.1.5 on 2023-02-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
