# Generated by Django 4.1.5 on 2023-02-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='residentialAreas',
            new_name='Residential_Areas',
        ),
    ]
