# Generated by Django 4.1.5 on 2023-06-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_residential_areas_residentialareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='have_loan',
            field=models.BooleanField(default=False),
        ),
    ]
