# Generated by Django 4.1.5 on 2023-02-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_residentialareas_residential_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/passport_photo/'),
        ),
    ]
