# Generated by Django 4.1.5 on 2023-09-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_residentialareas_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['mbr_no']},
        ),
    ]
