# Generated by Django 4.1.5 on 2023-10-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
