# Generated by Django 4.1.5 on 2023-06-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_have_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='have_loan',
        ),
    ]
