# Generated by Django 4.1.5 on 2023-02-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_gender_alter_members_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
