# Generated by Django 4.1.5 on 2023-02-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='image',
        ),
    ]
