# Generated by Django 4.1.5 on 2023-02-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_members_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='image',
        ),
    ]
